hydra:
  job:
    chdir: false

flow:
  sigma_min: 0.01
  base_scale: 1.

  network:
    time_embedding_dim: 8
    egnn:
      n_invariant_feat_hidden: 64
      n_blocks: 3
      mlp_units: [128, 128, 128]
    mace:
      readout_mlp_irreps: 16x0e + 16x1o
      hidden_irreps: 256x0e + 256x1o
      num_interactions: 2
      graph_type: fc  # fc / nbh / mace
      avg_num_neighbors: null  # null / average
      max_ell: 5
      variance_scaling: 0.001
      scale_output: true

task: dw4

training:
  use_ema: false
  optimizer:
      use_schedule: true  # mace default = false
      init_lr: 1e-4       # mace default = 0.01
      peak_lr: 1e-4
      end_lr: 0.
      n_iter_warmup: 10
  use_fixed_step_size: false
  save: false

  batch_size: 64
  seed: 0
  n_training_iter: 200
  plot_batch_size: 64
  eval_batch_size: 64
  train_set_size: 1000
  test_set_size: 1000
  eval_n_model_samples: null
  eval_exact_log_prob: true
  final_run: true
  n_checkpoints: 5
  n_eval: 5
  save_dir: ''
  save_in_wandb_dir: true


logger:
 list_logger: null
 pandas_logger:
   save_period: 1000 # how often to save the pandas dataframe as a csv
  # wandb:
  #   name: dw4_fm
  #   project: ecnf
  #   entity: kalyan0821
  #   tags: [dw4,flow_matching,final2,final3]
