hydra:
  job:
    chdir: false

flow:
  sigma_min: 0.000001
  base_scale: 2.
  network:
    type: egnn
    mlp_units: [128, 128, 128]
    n_blocks_egnn: 3
    n_invariant_feat_hidden: 128
    time_embedding_dim: 32


training:
  batch_size: 64
  seed: 0
  lr: 2e-4
  n_training_iter: 900
  plot_batch_size: 64
  eval_batch_size: 64
  train_set_size: null
  test_set_size: null
  eval_n_model_samples: null # Unused as there is no energy function.
  eval_exact_log_prob: false
  final_run: false
  n_checkpoints: 5
  n_eval: 10
  save: true
  save_dir: ''
  save_in_wandb_dir: true


logger:
#  list_logger: null
#  pandas_logger:
#    save_period: 1000 # how often to save the pandas dataframe as a csv
  wandb:
    name: qm9_fm_non_exact_density_BiggerNN_EvenlowerSigmaMin_longer
    project: fab
    entity: flow-ais-bootstrap
    tags: [qm9,flow_matching]